exit status: 1

stdout = """
def f: Int = let x: Int = (1, 2, 3)._0;
let y: Int = (1, 2, 3)._1;
x;
types of expressions:
8..35 = Int
23..32 = (Int, Int, Int)
24..25 = Int
27..28 = Int
30..31 = Int
34..35 = Int
types of patterns:
11..20 = (?0, ?1, ?2)
12..13 = ?0
15..16 = ?1
18..19 = ?2
metavars:
?0 = Int
?1 = Int
?2 = Int

def g: Int -> Int -> Int -> Int = fun(x: Int, y: Int, x: Int) => y;
types of expressions:
46..78 = Int -> Int -> Int -> Int
53..56 = Type
61..64 = Type
69..72 = Type
77..78 = Int
types of patterns:
50..51 = Int
58..59 = Int
66..67 = Int
"""

stderr = """
error: duplicate definition of local name `x`
  ┌─ tests/elab/errors/pattern_matching/duplicate_name.pion:1:19
  │
1 │ def f = let(x, y, x) = (1, 2, 3); x;
  │             -     ^ duplicate definition
  │             │      
  │             first definition

error: duplicate definition of local name `x`
  ┌─ tests/elab/errors/pattern_matching/duplicate_name.pion:3:29
  │
3 │ def g = fun(x: Int, y: Int, x: Int) => y;
  │             -               ^ duplicate definition
  │             │                
  │             first definition

aborting due to 2 previous errors
"""
